/* Generated By:JavaCC: Do not edit this line. sintacticoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface sintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_IF = 5;
  /** RegularExpression Id. */
  int T_ELSE = 6;
  /** RegularExpression Id. */
  int T_WHILE = 7;
  /** RegularExpression Id. */
  int T_FOR = 8;
  /** RegularExpression Id. */
  int T_FUNCTION = 9;
  /** RegularExpression Id. */
  int T_RETURN = 10;
  /** RegularExpression Id. */
  int T_ECHO = 11;
  /** RegularExpression Id. */
  int T_AIG_SUMA = 12;
  /** RegularExpression Id. */
  int T_ASIGNACION = 13;
  /** RegularExpression Id. */
  int T_SUMA = 14;
  /** RegularExpression Id. */
  int T_RESTA = 15;
  /** RegularExpression Id. */
  int T_MULTIPLICACION = 16;
  /** RegularExpression Id. */
  int T_DIVISION = 17;
  /** RegularExpression Id. */
  int T_IGUAL = 18;
  /** RegularExpression Id. */
  int T_DIFERENTE = 19;
  /** RegularExpression Id. */
  int T_MAYOR_QUE = 20;
  /** RegularExpression Id. */
  int T_MAYOR_O_IGUAL = 21;
  /** RegularExpression Id. */
  int T_MENOR_QUE = 22;
  /** RegularExpression Id. */
  int T_MENOR_O_IGUAL = 23;
  /** RegularExpression Id. */
  int T_PUNTO_COMA = 24;
  /** RegularExpression Id. */
  int T_PARIZQ = 25;
  /** RegularExpression Id. */
  int T_PARDER = 26;
  /** RegularExpression Id. */
  int T_LLAVE_IZQ = 27;
  /** RegularExpression Id. */
  int T_LLAVE_DER = 28;
  /** RegularExpression Id. */
  int T_NUMERO = 29;
  /** RegularExpression Id. */
  int T_VARIABLE = 30;
  /** RegularExpression Id. */
  int T_TEXTO = 31;
  /** RegularExpression Id. */
  int T_COMENTARIO_LINEA = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"function\"",
    "\"return\"",
    "\"echo\"",
    "\"+=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<T_NUMERO>",
    "<T_VARIABLE>",
    "<T_TEXTO>",
    "<T_COMENTARIO_LINEA>",
  };

}
